### ISSUE TITLE
AddConfigServer using custom ConfigServerClientSettings Not Working

### ISSUE THREAD

**Issue by baburajpb** [SteeltoeOSS/Configuration#25]
Some values in our VCAP_SERVICES json are encrypted, so I'm trying to add `ConfigServer` as a `ConfigurationSource` after decrypting those values and creating an instance of `ConfigServerClientSettings`. But during runtime `Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider` is still trying to load configurations from encrypted uri value and somehow ignoring the `configServerClientSettings` instance I have passed on during `ConfigureAppConfiguration`. Not sure if this is an issue or something I am doing incorrectly!

```
.ConfigureAppConfiguration((builderContext, configBuilder) => {
     configBuilder.SetBasePath(env.ContentRootPath)
        .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
        .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
        .AddEnvironmentVariables()
        .AddCommandLine(args)
        .AddCloudFoundry()
        .AddConfigServer(configServerClientSettings, logFactory);         
}
```

**Comment by TimHess** [comment]
Hi @baburajpb, 
To make sure we're on the same page, here's how I'm reading what you wrote:
1. Configuration settings for your Config Server are stored in an encrypted state inside of `VCAP_SERVICES`
1. You are retrieving and decrypting the config options and creating your own `ConfigServerClientSettings` with the decrypted values
1. You are passing your `ConfigServerClientSettings` into the configuration for the Config Server
1. The app fails to connect to the config server as it is using the encrypted values rather than the decrypted values

Have I understood correctly what's happening? It would also be good to know up front which Steeltoe Configuration package(s) you're referencing and what version of  .NET your app is using.

On a side note, if you're using Pivotal.Extensions.Configuration, you don't need on include `.AddCloudFoundry()` when building your app configuration as we already do that for you inside that version of `AddConfigServer`

**Comment by baburajpb** [comment]
YES you have understood the problem correctly.

Section from my csproj with Framework version and nuget package version below:
```
<PropertyGroup>
  <AssemblyName>Test</AssemblyName>
  <TargetFramework>netcoreapp2.0</TargetFramework>
  <RuntimeFrameworkVersion>2.0.0</RuntimeFrameworkVersion>
</PropertyGroup>
<ItemGroup>
  <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.4" />
  <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
  <PackageReference Include="Microsoft.AspNetCore.Rewrite" Version="2.0.2" />
  <PackageReference Include="Microsoft.Extensions.Http" Version="2.1.0" />
  <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="2.1.0" />
  <PackageReference Include="Pivotal.Discovery.ClientCore" Version="2.0.1" />
  <PackageReference Include="Pivotal.Extensions.Configuration.ConfigServerCore" Version="2.0.1" />
  <PackageReference Include="Steeltoe.CircuitBreaker.HystrixCore" Version="2.0.0" />
  <PackageReference Include="Steeltoe.CloudFoundry.ConnectorCore" Version="2.0.0" />
  <PackageReference Include="Steeltoe.Extensions.Configuration.CloudFoundryCore" Version="2.0.1" />
  <PackageReference Include="Steeltoe.CloudFoundry.Connector.EFCore" Version="2.0.0" />
  <PackageReference Include="Steeltoe.Management.CloudFoundryCore" Version="2.0.1" />
</ItemGroup>
```

Thanks for the tip about `AddCloudFoundry()`, I was using it to pass a custom instance of `ICloudFoundrySettingsReader` to decrypt values.

**Comment by TimHess** [comment]
It may take a little digging to find out what's happening here, I'm not seeing any unit tests that cover this scenario with passing in `ConfigServerClientSettings` from here.

In the meantime, have you considered using CredHub for locking up these credentials? The integration is quite seamless from the application's perspective and you wouldn't have to do this decryption: https://docs.pivotal.io/spring-cloud-services/1-5/service-broker-and-instances.html#using-credhub-for-service-instance-credentials

**Comment by TimHess** [comment]
I'm unclear on whether you're still using a custom `ICloudFoundrySettingsReader` and just omitted it from the code above or if you've removed it and are still having issues - could you share some more information on how you're expecting `AddCloudFoundry` with a custom settings reader to work in conjunction with connecting to the config server?

Also, a bit more directly - have you tried explicitly decrypting the settings before passing them into AddConfigServer?

**Comment by baburajpb** [comment]
I am not using `ICloudFoundrySettingsReader`, I wanted to use it to decrypt credentials so DiscoveryClient could use it.  Planning to add it back when I could get `AddConfigServer` working.

Yes tried explicitly decrypting values and verified they are decrypted and then passed on to `AddConfigServer` using instance of  `ConfigServerClientSettings`.

**Comment by TimHess** [comment]
The AddConfigServer method in the **Pivotal** library will always use the settings in VCAP_SERVICES. The `defaultSettings` parameter is only for setting _defaults_, it can't be used to override what's in the environment (I'll get the code comments updated shortly to better describe how it works). The latest version of this package in the dev feed will no longer add a `CloudFoundryConfigProvider` if one (eg: with your custom settings reader) is already present, so that is one option that should work for you.

The AddConfigServer method in the **Steeltoe** library will just take the "winning" configuration values. If you are using a custom deployment of Config server and not Spring Cloud Services, this library should also work for you if you place the decrypted config values into the expected locations under `spring:cloud:config`

Before proceeding with the custom settings decryption, I would encourage you to read up on using CredHub for service credential interpolation, particularly if you're using Spring Cloud Services.
