### ISSUE TITLE
.AddConfigServer(environment, ApplicationName, LogFactory), application name not propigated

### ISSUE THREAD

**Issue by stuwilliams-clgx** [SteeltoeOSS/Configuration#37]
When running in PCF using Blue/Green deployment the Blue/Green deployment `greeks` the application name to include versioning information. The configuration server client code picks up the application name from VCAP_APPLICATION which is a good default behavior, however, in cases where B/G deployment is being used, using the overload `.AddConfigServer(environment, *ApplicationName*, LogFactory)` allows the *ApplicationName* to be specified which would allow developers to specify the application name that appears in the `Manifest.yml` instead. However, this passed value is not respected at run time.

Reproduction Steps:
1. Set up Configuration Server
2. Set up a Git repository
3. Create `YML` files in the form of `{applicationname}-{environment}` with the same keys but unique values per environment (aka space)
4. Create a simple app that attempts to get the configuration from the configuration server and then outputs the values to STDOUT so we can see the values in the log
5. Deploy the application to one or more spaces using blue green deployment
6. Verify the app name is the application name in the `Manifest.yml` file plus the `greeked` suffix
7. dump the environment vars with `cf env ...` and the logs with `cf logs ... -recent`
8. Observe the issue

**Comment by hanserya** [comment]
Interesting, looks like the problem is rooted in the fact that the ConfigServerConfigurationProvider "initializes" the settings object that is injected into it. I wonder what the reason was for that design decision because it feels like a SRP violation - can anyone speak to that? It seems like the provider should just accept the settings object that is provided rather than manipulate it after-the-fact. I think a builder would solve that problem nicely.

Additionally, the provider is adding an awful lot of settings to the underlying Data collection for reasons that are not obvious. Perhaps there is code _somewhere_ in this offering that relies on having those settings available within the configuration context; however, I have not found evidence of that as-of yet. This is also a bummer because it prevents us from being able to reproduce the Spring look-and-feel wherein we could provide comma delimited lists of uri's and environments (by way of active spring profiles.) 

That could easily be handled as an application-specific implementation detail by simply registering multiple instances of the ConfigServerConfigurationProvider - which is a pattern supported generally by dotnet's configuration model. However; the fact that there appears to be some reliance on having those variables within the global configuration context puts a kibosh on that approach.

I am going to look at tossing a PR (or two) together to address this, but I at least wanted to initiate this dialog now in hopes of getting some idea of the team's thoughts on the matter. Specifically, I'd really like to understand the reasoning behind adding the settings "back" to the configuration context because that is (frankly, yet respectfully) a bit of an anti-pattern within the dotnet configuration model.

**Comment by hanserya** [comment]
Ahh - looks like adding spring:cloud:config values is done so that the ConfigServerClientSettingsOptions object can be bound to the configuration context. 

Would anyone be opposed to going down the named options route? It should be as simple as concatenating the name (when one is provided) as a prefix or a suffix to the existing section prefix. 

I would like to take it step further and make it such that each ConfigServerConfigurationProvider is responsible for a single intersection of a uri/profile/label within the three set Cartesian product  generated by splitting and cross-joining the comma delimited lists provided within each respective configuration element.  I know it is a change that is a little heavy, but should reduce the complexity of the provider itself by making the split operations a bootstrapping responsibility rather than a provider responsibility. 

FWIW - I am willing to drop the uri from consideration given that high-availability of services can (and, really - should) be achieved through methods that are not implementation details of a single application. However; it would maintain parity with the Java offering. As such, I am willing to make that happen if that is, as it were, "the will of the people."

**Comment by dtillman** [comment]
@stuwilliams-clgx : 

I believe the problem you were having with this was that spring.application.name was always being overridden by the name in the manifest.yml when you pushed the app to PCF.   This Steeltoe behavior was not consistent with Java Spring Boot applications.  

With Java based apps, if you DID NOT configure spring.application.name, then s.a.n would be set to the application name from manifest.yml. If you DID configure s.a.n, then it would be left alone and remain as configured.

With Steeltoe 2.2, to be released by end of 1st Qtr, we no longer override s.a.n when pushing to PCF (i.e. we follow what Java Spring Boot does).

Also another feature added to Steeltoe 2.2, which will likely will help with B/G, is we added Configuration Placeholder support.  This is a new Steeltoe Configuration Provider you can add to your ConfigurationBuilder that enables a Spring like feature called Property Placeholder and placeholder resolution. 

This enables you to define configuration keys with values that are placeholders and get resolved at runtime from the other configuration keys/values.  

The syntax of a placeholder is of the form: `${some:other:key}` or `${some:other:key?default_value_if_not_resolved}`. 

The `some:other:key` will be automatically resolved from the apps configuration (likely from some other configuration provider/source (e.g. EnvironmentVariable, CommandLine, etc.).  For example, you can use a placeholder for a configuration value that actually gets replaced by a command line parameter or a environment variable setting.

Have a look at the [unit tests](https://github.com/SteeltoeOSS/Configuration/blob/dev/test/Steeltoe.Extensions.Configuration.PlaceholderBase.Test/PlaceholderResolverExtensionsTest.cs) for examples.

Feel free to reopen another issue if we haven't addressed your needs with the changes in 2.2 of Steeltoe

Dave
